#!/usr/bin/env python3
"""Write side of a project wiki: init, index and log.

Stdlib-only. Creates the wiki skeleton without ever
overwriting an existing file, regenerates
Dashboards/Index.md from page frontmatter, and appends
dated entries to Dashboards/Log.md. Page content itself
is written by the agent or a human, not by this module.

Usage:
    import wiki_edit as we
    we.init(root)                  # skeleton + seed files
    we.build_index(root)           # Dashboards/Index.md
    we.append_log(root, "Added [[Postgres]]")

Created: 2026-09-15
Last updated: 2026-09-15
"""

import datetime as dt
import re
from pathlib import Path

import wiki_pages as wp

GITKEEP_DIRS = ["Inbox", "Wiki/Concepts", "Wiki/Entities",
                "Wiki/Summaries"]

README = """\
# {project} wiki

Persistent knowledge base for this project: interlinked
Markdown pages in Open Knowledge Format (OKF). Agents
search it with find and grep and follow `[[Page Name]]`
links; people can browse it as a local website.

- `Inbox/` - unsorted notes waiting to be filed.
- `Raw/` - immutable source documents, registered in
  `Raw/sources.md`.
- `Wiki/Summaries/` - one page per Raw source.
- `Wiki/Concepts/` - one page per idea, decision or
  pattern.
- `Wiki/Entities/` - one page per concrete thing:
  module, service, table, tool, vendor.
- `Dashboards/` - `Index.md` (generated), `Log.md`,
  `Topics.md`, and any overview pages.

Every page except `Index.md` and `Log.md` starts with
YAML frontmatter that has at least a `type`. Page names
are file names without `.md` and are unique across the
wiki. Start reading at `Dashboards/Index.md`.

The tools live outside the repo, in `~/.claude/wiki/`:

```bash
python3 ~/.claude/wiki/wiki_tools.py check
~/.claude/wiki/server_start.sh     # http://localhost:8020
```
"""

TOPICS = """\
---
type: Dashboard
title: Topics
description: The main topics of this wiki and the \
keywords for each.
tags: [plan]
---

# Topics

The plan for what this wiki covers. Each topic lists
keywords that are likely page names or search terms.

## Topic one

- Keywords: ...
"""

SOURCES = """\
# Raw sources

Registry of the immutable files in `Raw/`. Add a row
when a file is added; never edit the files themselves.

| File | Origin (URL or author) | Added | Notes |
|------|------------------------|-------|-------|
"""


# --------------------------------------------------------------
def write_new(path, text):
    """Write a file only if it does not exist yet."""
    if path.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


# --------------------------------------------------------------
def init(root):
    """Create folders and seed files; return new paths."""
    root = Path(root)
    made = []
    for d in wp.LAYOUT:
        (root / d).mkdir(parents=True, exist_ok=True)
    seeds = {
        "README.md": README.format(
            project=wp.project_name(root)),
        "Dashboards/Topics.md": TOPICS,
        "Raw/sources.md": SOURCES,
    }
    seeds.update({f"{d}/.gitkeep": "" for d in GITKEEP_DIRS})
    for name, text in seeds.items():
        if write_new(root / name, text):
            made.append(name)
    if not (root / "Dashboards/Log.md").exists():
        append_log(root, "Created the wiki skeleton.")
        made.append("Dashboards/Log.md")
    if not (root / "Dashboards/Index.md").exists():
        build_index(root)
        made.append("Dashboards/Index.md")
    return made


# --------------------------------------------------------------
def index_section(section, items):
    """Render one '## Section (n)' block of the index."""
    out = [f"## {section} ({len(items)})", ""]
    for page in items:
        meta, _ = wp.split_frontmatter(page.text())
        desc = str(meta.get("description", "")).strip()
        out.append(f"- [[{page.name}]]"
                   + (f" - {desc}" if desc else ""))
    return out + [""]


# --------------------------------------------------------------
def build_index(root):
    """Regenerate Dashboards/Index.md from the pages."""
    root = Path(root)
    by_sec = {sec: [] for sec in wp.SECTIONS}
    for page in wp.pages(root):
        if page.path.name.lower() != "index.md":
            by_sec[page.section].append(page)
    out = [
        f"# {wp.project_name(root)} wiki: index", "",
        "Every page, grouped by section. Generated by",
        "`wiki_tools.py index`; do not edit by hand.", "",
    ]
    for sec, items in by_sec.items():
        out += index_section(sec, items)
    path = root / "Dashboards" / "Index.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(out), encoding="utf-8")
    return path


# --------------------------------------------------------------
def append_log(root, message, today=None):
    """Add a bullet under today's '## YYYY-MM-DD' heading."""
    root = Path(root)
    path = root / "Dashboards" / "Log.md"
    day = today or dt.date.today().isoformat()
    if path.exists():
        text = path.read_text(encoding="utf-8")
    else:
        text = (f"# {wp.project_name(root)} wiki: log\n\n"
                "What changed in the wiki, oldest first.\n")
    days = re.findall(r"^## (\d{4}-\d{2}-\d{2})\s*$",
                      text, re.M)
    text = text.rstrip("\n") + "\n"
    if not days or days[-1] != day:
        text += f"\n## {day}\n\n"
    text += f"- {message.strip()}\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return path
